workflows:
  react-native-ios:
    name: React Native iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "MatchTalk.xcworkspace"
        XCODE_SCHEME: "MatchTalk"
      node: v18.18.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Expo Prebuild
        script: |
          # Generates the native iOS projects
          npx expo prebuild --platform ios
          # Patch Podfile with advanced flags for Xcode 16 and Architecture exclusions
          ruby -e "text=File.read('ios/Podfile'); text=text.gsub(/^platform :ios, .*/, \"platform :ios, '18.0'\"); new_text=text.gsub('post_install do |installer|', \"post_install do |installer|\\n    installer.pods_project.targets.each do |target|\\n      target.build_configurations.each do |config|\\n        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'\\n        config.build_settings['ENABLE_BITCODE'] = 'NO'\\n        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'\\n        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'\\n        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'\\n        config.build_settings['SWIFT_VERSION'] = '5.0'\\n        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = target.name == 'MatchTalk' ? 'YES' : 'NO'\\n        config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/usr/lib/swift']\\n        config.build_settings['DEAD_CODE_STRIPPING'] = 'NO'\\n      end\\n    end\"); File.write('ios/Podfile', new_text)"
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS App (Device - No Signing)
        script: |
          # Builds the app for Generic iOS Device (arm64) without code signing
          # This verifies the project builds for device architecture
          xcodebuild build \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
