workflows:
  react-native-ios:
    name: React Native iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "MatchTalk.xcworkspace"
        XCODE_SCHEME: "MatchTalk"
      node: v18.18.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Expo Prebuild
        script: |
          # Generates the native iOS projects
          npx expo prebuild --platform ios
          # Patch Podfile with advanced flags for Xcode 16: iOS 18.0 target, Disable Bitcode, Use gnu++20 C++ standard
          ruby -e "text=File.read('ios/Podfile'); new_text=text.gsub('post_install do |installer|', \"post_install do |installer|\\n    installer.pods_project.targets.each do |target|\\n      target.build_configurations.each do |config|\\n        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'\\n        config.build_settings['ENABLE_BITCODE'] = 'NO'\\n        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'\\n        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'\\n      end\\n    end\"); File.write('ios/Podfile', new_text)"
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS App (Release)
        script: |
          # Builds the app for simulator or device in Release mode
          xcodebuild build \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -sdk iphonesimulator \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
