workflows:
  react-native-ios:
    name: React Native iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "MatchTalk.xcworkspace"
        XCODE_SCHEME: "MatchTalk"
      node: v18.18.0
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: npm install --legacy-peer-deps
      - name: Expo Prebuild
        script: |
          # Generates the native iOS projects
          npx expo prebuild --platform ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS App (Simulator)
        script: |
          # Builds the app for simulator to verify compilation without code signing
          xcodebuild build \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
